### ISSUE TITLE
接着怎么操作呢？

### ISSUE THREAD

**Issue by luckypoem** [hisune/tinymvc-demo#1]
你好。我很想安装你这个建站程序。

root@localhost:~# cd 2.2
root@localhost:~/2.2# ls
app	       composer.lock  demo.sql	  README.md
composer.json  demo	      nginx.conf  vendor
root@localhost:~/2.2#

接着怎么操作呢？
非常感谢你的回复

**Comment by hisune** [comment]
按nginx.conf 来配置nginx的vhost的server，然后导入demo.sql即可

**Comment by luckypoem** [comment]
hi.

没成功。
http://tm-dm.smt.biz.st/ ，访问它，显示错误，如何解决？

**Comment by hisune** [comment]
1. 数据库的用户密码错误，在`app/Demo/config/config.php`中进行修改
2. `/usr/local/tinymvc-demo-site/2.2/app/Demo/var/Log/`目录不存在，新建这个目录并赋予777权限

**Comment by luckypoem** [comment]
操作了这2步，还是不行：
http://tm-dm.smt.biz.st/ ，访问它，显示错误：
PDOException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mysql_db.tm_dm_menu' doesn't exist

/usr/local/tinymvc-demo-site/2.2/vendor/hisune/tinymvc/Tiny/Database.php(line 88)

SQL: SELECT * FROM `tm_dm_menu` ORDER BY `order` desc

如何解决？谢谢你

**Comment by hisune** [comment]
请自己看错误提示，表不存在，默认表前缀是不存在的

**Comment by luckypoem** [comment]
hi.

我只会创建数据库的命令：
mysql> create database abc;
Query OK, 1 row affected (0.07 sec)

mysql>

不懂得如何创建数据库表。麻烦你就上面的错误，如何创建表，告诉我一下，好吗？
非常感谢！

**Comment by luckypoem** [comment]
看了一些教程：
mysql> create table mysql_db.tm_dm_menu;
ERROR 1113 (42000): A table must have at least 1 column
mysql>

接下去怎么操作，就不会了。能否不吝赐教呢？

**Comment by hisune** [comment]
@luckypoem 建议你初学使用YII2等成熟，文档多的框架：`https://github.com/yiisoft/yii2`。对于表的创建问题，最简单的方案是，用文本文件打开`https://github.com/hisune/tinymvc-demo/blob/master/demo.sql`，在`navicat for mysql`之类的客户端软件中直接执行`demo.sql`中的sql（前提是你先使用该客户端连接上了数据库并已创建好数据库）

**Comment by luckypoem** [comment]
hello.

我访问了https://raw.githubusercontent.com/hisune/tinymvc-demo/master/demo.sql ，

mysql> show tables;
+--------------------------+
| Tables_in_mysql_db       |
+--------------------------+
| admin                    |
| group                    |
| menu                     |
| wp232_comments           |
| wp232_links              |
| wp232_options            |
| wp232_postmeta           |
| wp232_posts              |
| wp232_term_relationships |
| wp232_term_taxonomy      |
| wp232_terms              |
| wp232_usermeta           |
| wp232_users              |
+--------------------------+
13 rows in set (0.00 sec)

mysql> CREATE TABLE `purview` (
    -> `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增id',
    -> `name` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT '名称',
    -> `data` text COLLATE utf8_unicode_ci NOT NULL COMMENT '权限内容',
    -> `created_at` timestamp NULL DEFAULT NULL,
    -> `updated_at` timestamp NULL DEFAULT NULL,
    -> PRIMARY KEY (`id`)
    -> ) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='权限配置表';
Query OK, 0 rows affected (0.02 sec)

mysql> show tables;
+--------------------------+
| Tables_in_mysql_db       |
+--------------------------+
| admin                    |
| group                    |
| menu                     |
| purview                  |
| wp232_comments           |
| wp232_links              |
| wp232_options            |
| wp232_postmeta           |
| wp232_posts              |
| wp232_term_relationships |
| wp232_term_taxonomy      |
| wp232_terms              |
| wp232_usermeta           |
| wp232_users              |
+--------------------------+
14 rows in set (0.00 sec)

mysql>

我从这行DROP TABLE IF EXISTS `admin`; 开始运行一直运行到这行：
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='权限配置表';

等于是删除又重建了数据表：admin,group,menu, purview .但是访问http://tm-dm.smt.biz.st/ 问题依旧。
怎么回事？
难道要首先运行SET FOREIGN_KEY_CHECKS=0; 而非首先运行DROP TABLE IF EXISTS `admin`;？

**Comment by hisune** [comment]
1. 把 admin,group,menu,purview这3个表名改为wp232_admin,wp232_group,wp232_menu,wp232_purview
2. 修改你的`app/Demo/config/config.php`配置文件中的database数组中的`prefix`的值为：`wp232_`

**Comment by luckypoem** [comment]
wp232_是我的wp博客的数据库的表前缀，会导致我的wp不正常吗？
如何新建一个表前缀？

**Comment by hisune** [comment]
不会

**Comment by luckypoem** [comment]
我看了http://www.cnblogs.com/BeginMan/p/3249472.html 里面“重命名表”的命令：
mysql> rename table admin to wp232_admin;
Query OK, 0 rows affected (0.15 sec)

mysql> rename table group to wp232_group;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group to wp232_group' at line 1
mysql>

怎么这条命令“rename table group to wp232_group;”遇错了呢？
而“rename table admin to wp232_admin;”却没遇错呢？
